# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Additional arguments to pass to Qt, without leading `--`. With
# QtWebEngine, some Chromium arguments (see
# https://peter.sh/experiments/chromium-command-line-switches/ for a
# list) will work.
# Type: List of String
c.qt.args = ['ppapi-widevine-path=/usr/lib64/qt5/plugins/ppapi/libwidevinecdm.so', 'link-settings=darkMode=4']

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Enable restore pages.
# Type: Bool
config.set('auto_save.session', True)

config.set('session.lazy_restore', True)


# qute-keepassxc
#config.bind('<Alt-Shift-u>', 'spawn --userscript qute-keepassxc --key', mode='insert')
#config.bind('pw', 'spawn --userscript qute-keepassxc --key', mode='normal')

# themes
config.source('themes/one.py')
